### ISSUE TITLE
LANG_001 Add new vocabulary

### ISSUE THREAD

**Issue by sw20-tugraz** [sw20-tug/ASD-Morning-5#1]
As a user I want to enter vocabulary (words/phrases in at least two different languages)

**Acceptance criteria:**
- Enter vocabulary in at least two different languages (e.g. German and English)

**Comment by ghost** [comment]
-Input with two different strings

**Comment by ghost** [comment]
-ability to save somewhere

**Comment by emreakca** [comment]
Database has to contain
- Language
- Word
- Rating
- Custom Tag
